// AUTO-GENERATED by lib/db/scripts/patch-course-content.mjs. Do not edit.
// What each course lesson contains, for catalog chips.
export interface LessonFeatures {
  videos: number; checks: number; exercises: number; examples: number;
  diagrams: number; cards: number; resources: number;
}
export const LESSON_FEATURES: Record<string, LessonFeatures> = {
  "architecture-beat-sheets": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 1 },
  "architecture-choosing-structure": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "architecture-heros-journey": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 0 },
  "architecture-scenes": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 1 },
  "architecture-three-acts": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 0 },
  "characters-antagonist": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 0, resources: 0 },
  "characters-backstory": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "characters-dialogue": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "characters-pov": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 0 },
  "characters-protagonist-wound": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 1 },
  "characters-supporting-cast": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "foundation-finding-idea": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "foundation-premise-promise": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 1 },
  "foundation-three-ingredients": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "foundation-what-is-story": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 1, resources: 0 },
  "foundation-why-people-read": { videos: 0, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 0, resources: 0 },
  "process-blank-page": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 0, resources: 0 },
  "process-endings": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 0, resources: 0 },
  "process-first-draft": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 0 },
  "process-openings": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 0, resources: 1 },
  "process-revision-passes": { videos: 2, checks: 2, exercises: 1, examples: 0, diagrams: 1, cards: 0, resources: 1 },
  "process-self-editing": { videos: 2, checks: 1, exercises: 1, examples: 0, diagrams: 0, cards: 1, resources: 1 },
  "process-when-to-stop": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "publishing-after-launch": { videos: 1, checks: 2, exercises: 1, examples: 0, diagrams: 0, cards: 1, resources: 0 },
  "publishing-audience": { videos: 0, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 0, resources: 0 },
  "publishing-cover-blurb": { videos: 0, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "publishing-marketing": { videos: 1, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "publishing-self-vs-traditional": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 1, cards: 0, resources: 1 },
  "world-description-pace": { videos: 2, checks: 2, exercises: 1, examples: 1, diagrams: 0, cards: 1, resources: 0 },
  "world-sensory-writing": { videos: 1, checks: 1, exercises: 1, examples: 1, diagrams: 0, cards: 0, resources: 0 },
  "world-setting-as-character": { videos: 2, checks: 2, exercises: 1, examples: 2, diagrams: 0, cards: 0, resources: 0 },
  "world-show-dont-tell": { videos: 2, checks: 1, exercises: 1, examples: 1, diagrams: 1, cards: 1, resources: 0 },
};
