export interface LiteraryAgent {
  id: string;
  name: string;
  agency: string;
  country: string;
  countryCode: string;
  region: string;
  genres: string[];
  description: string;
  website?: string;
  submissionUrl?: string;
  submissionEmail?: string;
  twitter?: string;
  manuscriptWishlist?: string;
  responseTimeWeeks?: number;
  acceptsUnsolicited: boolean;
  languages: string[];
  notes?: string;
}

export const AGENTS: LiteraryAgent[] = [
  // ── United States ─────────────────────────────────────────────────────────
  {
    id: "janklow-nesbit-us",
    name: "Janklow & Nesbit Associates",
    agency: "Janklow & Nesbit Associates",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Biography", "History", "Thriller"],
    description: "Founded in 1989, Janklow & Nesbit represents many of the most celebrated literary novelists, journalists, and historians working today. Sister office to Janklow & Nesbit UK.",
    website: "https://www.janklowandnesbit.com",
    submissionUrl: "https://www.janklowandnesbit.com/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Check agency website for current agents and submission preferences before querying.",
    responseTimeWeeks: 8,
  },
  {
    id: "wme-books",
    name: "WME Books",
    agency: "William Morris Endeavor (WME)",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Memoir", "Young Adult"],
    description: "WME's book department represents bestselling and award-winning authors across fiction, non-fiction, and screen rights. One of the largest talent agencies in the world.",
    website: "https://www.wmeagency.com",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Generally only accepts referred queries. Check individual agent profiles on the agency website.",
    responseTimeWeeks: 12,
  },
  {
    id: "caa-books",
    name: "CAA Books",
    agency: "Creative Artists Agency (CAA)",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Thriller", "Biography"],
    description: "CAA's literary department represents bestselling novelists and non-fiction authors, with strong film and TV rights integration. A major player in commercial and prestige publishing.",
    website: "https://www.caa.com",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Check agency website for current agents. Generally referral-based.",
    responseTimeWeeks: 12,
  },
  {
    id: "writers-house",
    name: "Writers House",
    agency: "Writers House",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Fiction", "Young Adult", "Children's", "Non-fiction", "Fantasy"],
    description: "Founded in 1973, Writers House is one of the largest literary agencies in the US. Represents many bestselling authors across fiction, non-fiction, children's, and YA.",
    website: "https://www.writershouse.com",
    submissionUrl: "https://www.writershouse.com/submission-guidelines",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Query individual agents. Each agent has their own submission preferences.",
    responseTimeWeeks: 8,
  },
  {
    id: "trident-media",
    name: "Trident Media Group",
    agency: "Trident Media Group",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Fiction", "Non-fiction", "Thriller", "Romance", "Young Adult", "Science Fiction"],
    description: "One of the largest literary agencies in the US, known for representing bestselling commercial and literary authors. Particularly strong in thriller, romance, and SFF.",
    website: "https://www.tridentmediagroup.com",
    submissionUrl: "https://www.tridentmediagroup.com/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "folio-literary",
    name: "Folio Literary Management",
    agency: "Folio Literary Management",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Fiction", "Young Adult", "Children's", "Non-fiction", "Memoir"],
    description: "New York agency with a broad client list spanning literary fiction, commercial fiction, and narrative non-fiction. Folio Jr. handles children's and YA.",
    website: "https://www.foliolit.com",
    submissionUrl: "https://www.foliolit.com/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Query individual agents directly via their listed email addresses.",
    responseTimeWeeks: 8,
  },
  {
    id: "inkwell-management",
    name: "InkWell Management",
    agency: "InkWell Management",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Memoir", "Biography", "History"],
    description: "Manhattan-based agency representing a distinguished list of bestselling and award-winning novelists, journalists, and historians.",
    website: "https://www.inkwellmanagement.com",
    submissionUrl: "https://www.inkwellmanagement.com/submissions",
    submissionEmail: "submissions@inkwellmanagement.com",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "icm-partners-books",
    name: "ICM Partners (CAA)",
    agency: "ICM Partners",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Memoir", "Biography"],
    description: "ICM's book department (now part of CAA) represents major literary novelists, historians, and journalists. Long history of bestseller and prize-winning representation.",
    website: "https://www.icmpartners.com",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Now part of CAA. Generally referral-based; check individual agent preferences.",
    responseTimeWeeks: 12,
  },
  {
    id: "sterling-lord",
    name: "Sterling Lord Literistic",
    agency: "Sterling Lord Literistic",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Biography", "History", "Poetry"],
    description: "Founded in 1952 by the agent of Jack Kerouac. One of the most storied literary agencies in the US, with a literary heritage spanning more than 70 years.",
    website: "https://www.sll.com",
    submissionUrl: "https://www.sll.com/submission-guidelines",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Query individual agents listed on the website with their preferred submission format.",
    responseTimeWeeks: 10,
  },
  {
    id: "aevitas-creative",
    name: "Aevitas Creative Management",
    agency: "Aevitas Creative Management",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Thriller", "Young Adult", "Children's"],
    description: "Formed by the merger of several major agencies, Aevitas represents bestselling and award-winning authors across all genres. Offices in New York, Boston, and London.",
    website: "https://aevitascreative.com",
    submissionUrl: "https://aevitascreative.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "bent-agency",
    name: "The Bent Agency",
    agency: "The Bent Agency",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Fiction", "Young Adult", "Children's", "Romance", "Thriller", "Fantasy"],
    description: "Boutique transatlantic agency founded by Jenny Bent, with offices in NY and London. Represents commercial and literary fiction, children's, and YA.",
    website: "https://www.thebentagency.com",
    submissionUrl: "https://www.thebentagency.com/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    manuscriptWishlist: "Strong voices, high-concept commercial fiction, YA with crossover appeal",
    responseTimeWeeks: 8,
  },
  {
    id: "park-fine",
    name: "Park & Fine Literary and Media",
    agency: "Park & Fine Literary and Media",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Thriller", "Young Adult"],
    description: "Manhattan agency representing a wide range of bestselling and prize-winning fiction and non-fiction. Strong film/TV rights operation.",
    website: "https://parkfine.com",
    submissionUrl: "https://parkfine.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "dystel-goderich-bourret",
    name: "Dystel, Goderich & Bourret",
    agency: "Dystel, Goderich & Bourret",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Fiction", "Non-fiction", "Young Adult", "Children's", "Memoir", "Romance"],
    description: "Long-established New York agency representing a wide range of bestselling and award-winning authors across fiction and non-fiction.",
    website: "https://www.dystel.com",
    submissionUrl: "https://www.dystel.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Query individual agents via email; see website for guidelines.",
    responseTimeWeeks: 8,
  },
  {
    id: "levine-greenberg-rostan",
    name: "Levine Greenberg Rostan Literary Agency",
    agency: "Levine Greenberg Rostan Literary Agency",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Young Adult", "Children's", "Biography"],
    description: "Full-service New York agency representing fiction, non-fiction, illustrated books, children's, and YA. Particular strength in narrative non-fiction.",
    website: "https://www.lgrliterary.com",
    submissionUrl: "https://www.lgrliterary.com/submit/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "sanford-greenburger",
    name: "Sanford J. Greenburger Associates",
    agency: "Sanford J. Greenburger Associates",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Young Adult", "Memoir"],
    description: "One of the oldest literary agencies in New York, founded in 1932. Represents bestselling fiction and non-fiction authors, including Dan Brown.",
    website: "https://greenburger.com",
    submissionUrl: "https://greenburger.com/submission-guidelines/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "jane-rotrosen",
    name: "Jane Rotrosen Agency",
    agency: "Jane Rotrosen Agency",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Romance", "Thriller", "Crime Fiction", "Fiction", "Young Adult"],
    description: "Boutique New York agency specializing in commercial fiction — romance, thrillers, suspense, women's fiction. Founded in 1974.",
    website: "https://janerotrosen.com",
    submissionUrl: "https://janerotrosen.com/about-us/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    manuscriptWishlist: "Commercial romance, thriller, suspense, women's fiction with strong hooks",
    responseTimeWeeks: 8,
  },
  {
    id: "curtis-brown-us",
    name: "Curtis Brown, Ltd.",
    agency: "Curtis Brown, Ltd. (US)",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Young Adult", "Children's", "Memoir", "Biography"],
    description: "New York office of the long-established Curtis Brown agency, founded in 1914. Represents distinguished fiction and non-fiction across all categories.",
    website: "https://www.curtisbrown.com",
    submissionUrl: "https://www.curtisbrown.com/submission-guidelines",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Independent from Curtis Brown UK. Each agent has their own submission preferences.",
    responseTimeWeeks: 10,
  },
  {
    id: "mccormick-literary",
    name: "McCormick Literary",
    agency: "McCormick Literary",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Biography", "History"],
    description: "Founded by David McCormick, this New York agency represents many of the most distinguished literary novelists and non-fiction authors of the past two decades.",
    website: "https://www.mccormicklit.com",
    submissionEmail: "submissions@mccormicklit.com",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },

  // ── United Kingdom ─────────────────────────────────────────────────────────
  {
    id: "curtis-brown-uk",
    name: "Curtis Brown UK",
    agency: "Curtis Brown UK",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Fiction", "Non-fiction", "Young Adult", "Children's", "Thriller"],
    description: "Founded in 1899, Curtis Brown is the UK's largest literary and talent agency, representing many of the leading authors of British literature, journalism, and screenwriting.",
    website: "https://www.curtisbrown.co.uk",
    submissionUrl: "https://www.curtisbrown.co.uk/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Query individual agents through the website's submission portal.",
    responseTimeWeeks: 10,
  },
  {
    id: "united-agents",
    name: "United Agents",
    agency: "United Agents",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Young Adult", "Children's", "Memoir", "Biography"],
    description: "London agency formed by senior agents from PFD, representing a distinguished list of literary novelists, screenwriters, and non-fiction authors.",
    website: "https://www.unitedagents.co.uk",
    submissionUrl: "https://www.unitedagents.co.uk/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 10,
  },
  {
    id: "felicity-bryan",
    name: "Felicity Bryan Associates",
    agency: "Felicity Bryan Associates",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "History", "Biography", "Memoir"],
    description: "Oxford-based agency long known for representing serious literary fiction and intelligent non-fiction. Strong international rights operation.",
    website: "https://www.felicitybryan.com",
    submissionUrl: "https://www.felicitybryan.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 10,
  },
  {
    id: "rcw-agency",
    name: "Rogers, Coleridge & White",
    agency: "Rogers, Coleridge & White (RCW)",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Children's", "Memoir", "Biography", "Poetry"],
    description: "Prestigious London literary agency representing many of the UK's most celebrated literary novelists, journalists, and biographers. Founded in 1987.",
    website: "https://www.rcwlitagency.com",
    submissionUrl: "https://www.rcwlitagency.com/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 12,
  },
  {
    id: "andrew-nurnberg",
    name: "Andrew Nurnberg Associates",
    agency: "Andrew Nurnberg Associates",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Translated Literature", "History", "Biography"],
    description: "London-based agency with offices across Europe and Asia. Specializes in international rights and translation deals for literary and non-fiction works.",
    website: "https://www.andrewnurnberg.com",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Primarily handles international rights. Check agency website for current submission policies.",
    responseTimeWeeks: 10,
  },
  {
    id: "wylie-agency",
    name: "The Wylie Agency",
    agency: "The Wylie Agency",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Biography", "History", "Philosophy"],
    description: "Andrew Wylie's powerhouse agency, with offices in London and New York. Represents Nobel laureates, Booker Prize winners, and many of the most important literary voices.",
    website: "https://www.wylieagency.com",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Strictly referral-based. Does not accept unsolicited queries.",
    responseTimeWeeks: 12,
  },
  {
    id: "am-heath",
    name: "A.M. Heath Literary Agents",
    agency: "A.M. Heath",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Fiction", "Non-fiction", "Crime Fiction", "Young Adult", "Children's"],
    description: "Founded in 1919, A.M. Heath is one of the UK's oldest literary agencies. Represents acclaimed fiction and non-fiction across all genres.",
    website: "https://www.amheath.com",
    submissionUrl: "https://www.amheath.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "david-higham",
    name: "David Higham Associates",
    agency: "David Higham Associates",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Children's", "Young Adult", "Biography", "Memoir"],
    description: "London agency founded in 1935, representing many of the UK's most prestigious literary novelists and non-fiction authors. Also represents major children's authors.",
    website: "https://www.davidhigham.co.uk",
    submissionUrl: "https://www.davidhigham.co.uk/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 10,
  },
  {
    id: "greene-heaton",
    name: "Greene & Heaton",
    agency: "Greene & Heaton",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Fiction", "Non-fiction", "Thriller", "Crime Fiction", "Biography"],
    description: "London literary agency representing a wide range of bestselling and prize-winning fiction and non-fiction. Independent and founder-led for over 60 years.",
    website: "https://www.greeneheaton.co.uk",
    submissionUrl: "https://www.greeneheaton.co.uk/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "conville-walsh",
    name: "Conville & Walsh (C&W Agency)",
    agency: "C&W Agency (part of Curtis Brown)",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Young Adult", "Memoir"],
    description: "London agency, now part of the Curtis Brown group. Known for representing prize-winning literary fiction and major non-fiction works.",
    website: "https://www.cwagency.co.uk",
    submissionUrl: "https://www.cwagency.co.uk/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 10,
  },
  {
    id: "janklow-nesbit-uk",
    name: "Janklow & Nesbit UK",
    agency: "Janklow & Nesbit UK",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Memoir", "Biography"],
    description: "London office of the major US agency. Represents bestselling and award-winning literary fiction and serious non-fiction in the UK and Commonwealth markets.",
    website: "https://www.janklowandnesbit.co.uk",
    submissionUrl: "https://www.janklowandnesbit.co.uk/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "blake-friedmann",
    name: "Blake Friedmann Literary Agency",
    agency: "Blake Friedmann",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Fiction", "Non-fiction", "Thriller", "Crime Fiction", "Romance"],
    description: "Long-established London literary and film/TV agency. Represents commercial and literary fiction, non-fiction, and screenwriters.",
    website: "https://www.blakefriedmann.co.uk",
    submissionUrl: "https://www.blakefriedmann.co.uk/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "soho-agency",
    name: "The Soho Agency",
    agency: "The Soho Agency",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Fiction", "Non-fiction", "Memoir", "Biography", "Thriller"],
    description: "London agency formed from a merger of LAW and Christopher Little. Represents bestselling and prize-winning fiction and non-fiction.",
    website: "https://www.thesohoagency.co.uk",
    submissionUrl: "https://www.thesohoagency.co.uk/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },

  // ── Canada ─────────────────────────────────────────────────────────────────
  {
    id: "westwood-creative",
    name: "Westwood Creative Artists",
    agency: "Westwood Creative Artists",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Biography", "Young Adult"],
    description: "Canada's largest literary agency, based in Toronto. Represents many of Canada's most prominent literary novelists and non-fiction authors.",
    website: "https://www.wcaltd.com",
    submissionUrl: "https://www.wcaltd.com/submissions",
    acceptsUnsolicited: true,
    languages: ["English", "French"],
    responseTimeWeeks: 10,
  },
  {
    id: "cooke-mcdermid",
    name: "CookeMcDermid Literary Management",
    agency: "CookeMcDermid",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Young Adult", "Children's"],
    description: "Toronto-based agency representing leading Canadian literary fiction and non-fiction. Many clients on award shortlists and bestseller lists.",
    website: "https://cookemcdermid.com",
    submissionUrl: "https://cookemcdermid.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "transatlantic-agency",
    name: "Transatlantic Agency",
    agency: "Transatlantic Agency",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    genres: ["Literary Fiction", "Fiction", "Non-fiction", "Young Adult", "Children's", "Memoir"],
    description: "Toronto agency with offices across North America. Represents fiction and non-fiction authors across all categories with strong North American and international reach.",
    website: "https://transatlanticagency.com",
    submissionUrl: "https://transatlanticagency.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },

  // ── Australia & New Zealand ────────────────────────────────────────────────
  {
    id: "camerons-management",
    name: "Cameron's Management",
    agency: "Cameron's Management",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    genres: ["Literary Fiction", "Non-fiction", "Young Adult", "Children's", "Memoir"],
    description: "Long-established Sydney agency representing many of Australia's leading literary novelists, non-fiction writers, and screenwriters.",
    website: "https://www.cameronsmanagement.com.au",
    submissionUrl: "https://www.cameronsmanagement.com.au/submissions",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Currently closed to most unsolicited submissions. Check website for open submission windows.",
    responseTimeWeeks: 12,
  },
  {
    id: "curtis-brown-au",
    name: "Curtis Brown Australia",
    agency: "Curtis Brown Australia",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    genres: ["Literary Fiction", "Fiction", "Non-fiction", "Children's", "Young Adult", "Crime Fiction"],
    description: "Sydney-based agency, the Australian arm of Curtis Brown. Represents many of Australia's best-known literary and commercial authors.",
    website: "https://www.curtisbrown.com.au",
    submissionUrl: "https://www.curtisbrown.com.au/submission-guidelines",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 10,
  },
  {
    id: "jenny-darling",
    name: "Jenny Darling & Associates",
    agency: "Jenny Darling & Associates",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Young Adult", "Biography"],
    description: "Melbourne agency known for representing prize-winning Australian literary fiction and serious non-fiction.",
    website: "https://www.jennydarling.com.au",
    submissionEmail: "info@jennydarling.com.au",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Generally closed to unsolicited queries. Check website for current status.",
    responseTimeWeeks: 12,
  },

  // ── Additional US agencies ─────────────────────────────────────────────────
  {
    id: "writers-house-jr",
    name: "Writers House Jr. (Children's)",
    agency: "Writers House",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Children's", "Young Adult", "Fantasy", "Science Fiction"],
    description: "Children's division of Writers House — agents who specialize in picture books, middle grade, and YA. Many of the biggest YA franchises started here.",
    website: "https://www.writershouse.com",
    submissionUrl: "https://www.writershouse.com/submission-guidelines",
    acceptsUnsolicited: true,
    languages: ["English"],
    manuscriptWishlist: "High-concept middle grade and YA, picture books with fresh voices",
    responseTimeWeeks: 8,
  },
  {
    id: "donald-maass",
    name: "Donald Maass Literary Agency",
    agency: "Donald Maass Literary Agency",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Fiction", "Science Fiction", "Fantasy", "Thriller", "Romance", "Literary Fiction"],
    description: "New York agency founded in 1980, known for representing commercial and literary fiction, especially SFF, thriller, and romance. Donald Maass is also a respected author of craft books.",
    website: "https://maassagency.com",
    submissionUrl: "https://maassagency.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "kt-literary",
    name: "kt literary",
    agency: "kt literary",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Young Adult", "Children's", "Romance", "Fantasy", "Science Fiction", "Fiction"],
    description: "Founded by Kate Testerman, this Colorado-based agency specializes in middle grade, YA, and adult fiction with a strong digital-first sensibility.",
    website: "https://ktliterary.com",
    submissionUrl: "https://ktliterary.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    manuscriptWishlist: "MG and YA with strong hooks, fantasy and contemporary, diverse voices",
    responseTimeWeeks: 6,
  },
  {
    id: "new-leaf-literary",
    name: "New Leaf Literary & Media",
    agency: "New Leaf Literary & Media",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Young Adult", "Fantasy", "Science Fiction", "Children's", "Fiction", "Romance"],
    description: "New York agency known for representing bestselling YA, MG, and SFF. Strong film/TV rights integration.",
    website: "https://www.newleafliterary.com",
    submissionUrl: "https://www.newleafliterary.com/submission-guidelines",
    acceptsUnsolicited: true,
    languages: ["English"],
    manuscriptWishlist: "Genre fiction with crossover potential, YA with cinematic worldbuilding",
    responseTimeWeeks: 6,
  },
  {
    id: "fuse-literary",
    name: "Fuse Literary",
    agency: "Fuse Literary",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Fiction", "Non-fiction", "Young Adult", "Romance", "Fantasy", "Memoir"],
    description: "Bicoastal US agency representing a wide variety of fiction and non-fiction. Known for embracing hybrid publishing and digital-first approaches alongside traditional deals.",
    website: "https://www.fuseliterary.com",
    submissionUrl: "https://www.fuseliterary.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 6,
  },
  {
    id: "bookends-literary",
    name: "BookEnds Literary Agency",
    agency: "BookEnds Literary Agency",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Romance", "Mystery", "Thriller", "Young Adult", "Fiction", "Children's"],
    description: "New Jersey agency specializing in commercial fiction — particularly strong in romance, mystery, and women's fiction. Founded by Jessica Faust.",
    website: "https://bookendsliterary.com",
    submissionUrl: "https://bookendsliterary.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    manuscriptWishlist: "Romance with fresh hooks, cozy mysteries, women's fiction, MG and YA",
    responseTimeWeeks: 6,
  },
  {
    id: "jdla",
    name: "Jill Grinberg Literary Management",
    agency: "Jill Grinberg Literary Management",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Young Adult", "Children's", "Non-fiction", "Fantasy", "Science Fiction"],
    description: "Brooklyn agency representing critically acclaimed and bestselling fiction and non-fiction, including major literary YA and children's titles.",
    website: "https://www.jillgrinbergliterary.com",
    submissionUrl: "https://www.jillgrinbergliterary.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "barbara-braun",
    name: "Barbara Braun Associates",
    agency: "Barbara Braun Associates",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Historical Fiction", "Non-fiction", "Biography"],
    description: "New York boutique agency specializing in literary and historical fiction, art-related non-fiction, and biography.",
    website: "https://www.barbarabraunagency.com",
    submissionUrl: "https://www.barbarabraunagency.com/submissions.html",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "irene-goodman",
    name: "Irene Goodman Literary Agency",
    agency: "Irene Goodman Literary Agency",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Romance", "Historical Fiction", "Mystery", "Thriller", "Non-fiction"],
    description: "New York agency with strong client list in historical fiction, romance, mystery, and narrative non-fiction.",
    website: "https://www.irenegoodman.com",
    submissionUrl: "https://www.irenegoodman.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 6,
  },
  {
    id: "dijkstra-agency",
    name: "Sandra Dijkstra Literary Agency",
    agency: "Sandra Dijkstra Literary Agency",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Memoir", "Young Adult", "History", "Biography"],
    description: "California agency that represented Amy Tan, Lisa See, and many other bestselling literary authors. Known for discovering important new voices.",
    website: "https://dijkstraagency.com",
    submissionUrl: "https://dijkstraagency.com/submissions.php",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },

  // ── Additional UK agencies ─────────────────────────────────────────────────
  {
    id: "marjacq",
    name: "Marjacq Scripts",
    agency: "Marjacq Scripts",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Fiction", "Non-fiction", "Crime Fiction", "Thriller", "Young Adult", "Children's"],
    description: "Long-established London agency representing fiction, non-fiction, screenwriters, and directors. Particularly known for crime and thriller representation.",
    website: "https://marjacq.com",
    submissionUrl: "https://marjacq.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "darley-anderson",
    name: "Darley Anderson Literary Agency",
    agency: "Darley Anderson",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Thriller", "Crime Fiction", "Romance", "Young Adult", "Children's", "Non-fiction"],
    description: "London agency known for representing many of the UK's biggest commercial fiction authors — thrillers, crime, romance, and women's fiction.",
    website: "https://www.darleyanderson.com",
    submissionUrl: "https://www.darleyanderson.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    manuscriptWishlist: "Page-turning commercial thrillers and crime, women's fiction with broad appeal",
    responseTimeWeeks: 8,
  },
  {
    id: "lba-books",
    name: "LBA Books",
    agency: "LBA Books",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Fiction", "Non-fiction", "Thriller", "Romance", "Young Adult", "Children's"],
    description: "London agency representing commercial and literary fiction and non-fiction, with strong international rights and screen rights operations.",
    website: "https://www.lbabooks.com",
    submissionUrl: "https://www.lbabooks.com/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "watson-little",
    name: "Watson, Little Literary Agency",
    agency: "Watson, Little",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Fiction", "Non-fiction", "Children's", "Young Adult", "Memoir"],
    description: "Long-established London agency representing fiction, non-fiction, and children's authors across all categories.",
    website: "https://www.watsonlittle.com",
    submissionUrl: "https://www.watsonlittle.com/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 8,
  },
  {
    id: "ki-agency",
    name: "Ki Agency",
    agency: "Ki Agency",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Fiction", "Non-fiction", "Crime Fiction", "Thriller", "Science Fiction", "Fantasy"],
    description: "London boutique agency representing fiction and non-fiction, including science fiction, fantasy, crime, and literary works.",
    website: "https://www.ki-agency.co.uk",
    submissionUrl: "https://www.ki-agency.co.uk/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    responseTimeWeeks: 6,
  },

  // ── France ─────────────────────────────────────────────────────────────────
  {
    id: "agence-litteraire-pierre-astier",
    name: "Astier-Pécher Literary Agency",
    agency: "Astier-Pécher Literary & Film Agency",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Translated Literature", "Memoir"],
    description: "Paris-based agency representing French and international literary authors. Strong connections with European, Arabic, and Latin American literary publishers.",
    website: "https://www.astier-pecher.com",
    submissionEmail: "contact@astier-pecher.com",
    acceptsUnsolicited: true,
    languages: ["French", "English"],
    responseTimeWeeks: 12,
  },
  {
    id: "agence-litteraire-michelle-lapautre",
    name: "Agence Michelle Lapautre",
    agency: "Agence Michelle Lapautre",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Translated Literature"],
    description: "Long-established Paris literary agency representing French rights for major international authors and selling French literary fiction abroad.",
    website: "https://www.agence-lapautre.com",
    submissionEmail: "agence@lapautre.com",
    acceptsUnsolicited: false,
    languages: ["French", "English"],
    notes: "Check agency website for current agents and submission policies.",
    responseTimeWeeks: 12,
  },

  // ── Germany ────────────────────────────────────────────────────────────────
  {
    id: "ag-literatur",
    name: "AG Literatur",
    agency: "AG Literatur",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Biography", "Memoir"],
    description: "Munich-based literary agency representing German-language authors and selling foreign rights for major international literary works.",
    website: "https://www.ag-literatur.de",
    submissionEmail: "info@ag-literatur.de",
    acceptsUnsolicited: false,
    languages: ["German", "English"],
    notes: "Check agency website for current agents accepting submissions.",
    responseTimeWeeks: 12,
  },
  {
    id: "michael-meller",
    name: "Michael Meller Literary Agency",
    agency: "Michael Meller Literary Agency",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Memoir", "Biography"],
    description: "One of Germany's leading literary agencies, based in Munich. Represents German authors internationally and major international authors in the German market.",
    website: "https://www.melleragency.com",
    submissionEmail: "info@melleragency.com",
    acceptsUnsolicited: false,
    languages: ["German", "English"],
    notes: "Check agency website for current agents and submission guidelines.",
    responseTimeWeeks: 12,
  },

  // ── Spain & Latin America ──────────────────────────────────────────────────
  {
    id: "carmen-balcells",
    name: "Agencia Literaria Carmen Balcells",
    agency: "Agencia Literaria Carmen Balcells",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Poetry", "Memoir"],
    description: "Legendary Barcelona literary agency founded by Carmen Balcells. Represented Gabriel García Márquez, Mario Vargas Llosa, and many Spanish-language Nobel laureates.",
    website: "https://www.agenciabalcells.com",
    submissionEmail: "info@agenciabalcells.com",
    acceptsUnsolicited: false,
    languages: ["Spanish", "English"],
    notes: "Highly selective. Check agency website for current agents and policies.",
    responseTimeWeeks: 12,
  },
  {
    id: "antonia-kerrigan",
    name: "Antonia Kerrigan Agencia Literaria",
    agency: "Antonia Kerrigan Agencia Literaria",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Crime Fiction", "Memoir"],
    description: "Barcelona-based agency representing many of the leading Spanish-language literary and commercial authors. Strong international rights operation.",
    website: "https://www.antoniakerrigan.com",
    submissionEmail: "info@antoniakerrigan.com",
    acceptsUnsolicited: false,
    languages: ["Spanish", "English"],
    notes: "Check agency website for current agents and submission policies.",
    responseTimeWeeks: 12,
  },

  // ── India / South Asia ─────────────────────────────────────────────────────
  {
    id: "jacaranda-literary",
    name: "Jacaranda Literary Agency",
    agency: "Jacaranda Literary Agency",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    genres: ["Literary Fiction", "Non-fiction", "Young Adult", "Children's", "Memoir"],
    description: "Delhi-based literary agency representing Indian and South Asian authors across literary fiction, non-fiction, and children's books.",
    website: "https://jacarandaliteraryagency.com",
    submissionEmail: "info@jacarandaliteraryagency.com",
    acceptsUnsolicited: true,
    languages: ["English", "Hindi"],
    responseTimeWeeks: 8,
  },
  {
    id: "writers-side",
    name: "The Writers' Side",
    agency: "The Writers' Side",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    genres: ["Fiction", "Non-fiction", "Young Adult", "Memoir", "Self-help"],
    description: "Mumbai-based literary agency representing Indian authors across genres, with strong relationships with the major Indian publishing houses.",
    website: "https://www.writersside.com",
    submissionEmail: "info@writersside.com",
    acceptsUnsolicited: true,
    languages: ["English", "Hindi"],
    responseTimeWeeks: 6,
  },

  // ── Middle East & North Africa ─────────────────────────────────────────────
  {
    id: "raya-agency",
    name: "RAYA Agency for Arabic Literature",
    agency: "RAYA Agency",
    country: "Lebanon",
    countryCode: "LB",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Literary Fiction", "Non-fiction", "Translated Literature", "Poetry"],
    description: "Founded by Yasmina Jraissati, RAYA represents Arabic-language authors and sells their works to international publishers. The leading agency dedicated to Arab literature in translation.",
    website: "https://www.rayaagency.com",
    submissionEmail: "info@rayaagency.com",
    acceptsUnsolicited: true,
    languages: ["Arabic", "English", "French"],
    manuscriptWishlist: "Literary Arabic fiction with international appeal, especially debut voices",
    responseTimeWeeks: 10,
  },
];
