export interface Publisher {
  id: string;
  name: string;
  country: string;
  countryCode: string;
  city?: string;
  region: string;
  genres: string[];
  description: string;
  website: string;
  submissionUrl?: string;
  submissionEmail?: string;
  acceptsUnsolicited: boolean;
  languages: string[];
  notes?: string;
  founded?: number;
  rating?: number;           // 1–5 stars
  submissionType?: "digital" | "physical" | "both";
  logoColor?: string;        // hex accent for logo tile
}

export const PUBLISHERS: Publisher[] = [
  // ── United States ─────────────────────────────────────────────────────────
  {
    id: "sourcebooks",
    name: "Sourcebooks",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Fiction", "Romance", "Young Adult", "Children's", "Non-fiction", "Self-help"],
    description: "One of the largest independent publishers in the US, known for commercial fiction, romance, and YA. Actively seeks new voices and considers submissions from unagented authors through specific imprints.",
    website: "https://www.sourcebooks.com",
    submissionUrl: "https://www.sourcebooks.com/submission-guidelines.html",
    acceptsUnsolicited: true,
    languages: ["English"],
    founded: 1987,
  },
  {
    id: "algonquin",
    name: "Algonquin Books",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Non-fiction", "Narrative Non-fiction"],
    description: "Chapel Hill-based independent publisher celebrated for literary fiction and narrative non-fiction. Known for launching debut authors and discovering distinctive new voices.",
    website: "https://www.algonquin.com",
    submissionUrl: "https://www.algonquin.com/submissions/",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Accepts submissions via literary agents only.",
    founded: 1983,
  },
  {
    id: "tor-books",
    name: "Tor Books",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Science Fiction", "Fantasy", "Horror", "Thriller"],
    description: "The premier publisher of science fiction and fantasy in the US. Part of Macmillan Publishers, Tor has launched some of the most beloved sci-fi and fantasy series of the last four decades.",
    website: "https://www.tor.com",
    submissionUrl: "https://www.tor.com/about-tor/submissions/",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Accepts agented submissions only; Tor.com publishes novelettes and novellas open to direct queries.",
    founded: 1980,
  },
  {
    id: "chronicle-books",
    name: "Chronicle Books",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Children's", "Art & Design", "Lifestyle", "Gift Books", "Illustrated Non-fiction"],
    description: "San Francisco-based publisher known for beautifully designed books, children's titles, and lifestyle content. Open to fresh perspectives and original voices.",
    website: "https://www.chroniclebooks.com",
    submissionUrl: "https://www.chroniclebooks.com/pages/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    founded: 1967,
  },
  {
    id: "baen-books",
    name: "Baen Books",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Science Fiction", "Fantasy", "Military Fiction"],
    description: "Independent publisher specializing in science fiction and fantasy, particularly military SF. One of the few major publishers that still accepts unsolicited novel manuscripts directly.",
    website: "https://www.baen.com",
    submissionUrl: "https://www.baen.com/baen-books-submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Accepts full novel manuscripts directly. Response time is 9–12 months.",
    founded: 1983,
  },
  {
    id: "university-chicago-press",
    name: "University of Chicago Press",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Academic", "Non-fiction", "History", "Philosophy", "Social Sciences"],
    description: "One of the largest academic presses in the world. Publishes scholarly works across the humanities, social sciences, and sciences, as well as trade non-fiction.",
    website: "https://www.press.uchicago.edu",
    submissionUrl: "https://www.press.uchicago.edu/ucp/books/for_authors/index.html",
    acceptsUnsolicited: true,
    languages: ["English"],
    founded: 1891,
  },
  {
    id: "seven-stories",
    name: "Seven Stories Press",
    country: "United States",
    countryCode: "US",
    region: "North America",
    genres: ["Literary Fiction", "Politics", "Human Rights", "Social Justice", "Non-fiction"],
    description: "Independent press publishing award-winning literary fiction and non-fiction with a focus on social and political issues. Publishes writers from around the world in translation.",
    website: "https://www.sevenstories.com",
    submissionUrl: "https://www.sevenstories.com/pages/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    founded: 1995,
  },
  {
    id: "penguin-random-house",
    name: "Penguin Random House",
    country: "United States",
    countryCode: "US",
    city: "New York",
    region: "North America",
    genres: ["Fiction", "Non-fiction", "Literary Fiction", "Thriller", "Romance", "Children's", "Biography", "Science Fiction", "Young Adult"],
    description: "The world's largest trade book publisher, home to iconic imprints including Viking, Knopf, Doubleday, Bantam, Crown, and Pantheon. Publishes across every genre and language globally.",
    website: "https://www.penguinrandomhouse.com",
    submissionUrl: "https://www.penguinrandomhouse.com/about/submissions/",
    acceptsUnsolicited: false,
    languages: ["English", "Spanish", "German", "Portuguese", "French"],
    notes: "Accepts submissions via literary agents only for most imprints. Some imprints like Loveswept accept digital submissions.",
    founded: 2013,
    rating: 4.8,
    submissionType: "digital",
    logoColor: "#e11d48",
  },

  // ── Canada ─────────────────────────────────────────────────────────────────
  {
    id: "house-of-anansi",
    name: "House of Anansi Press",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    genres: ["Literary Fiction", "Poetry", "Non-fiction", "Essays"],
    description: "One of Canada's most celebrated literary publishers, known for publishing some of Canada's best writers including Margaret Atwood. Focuses on quality literary writing.",
    website: "https://www.houseofanansi.com",
    submissionUrl: "https://www.houseofanansi.com/pages/submissions",
    acceptsUnsolicited: false,
    languages: ["English", "French"],
    notes: "Accepts submissions from Canadian authors via literary agents. Publishes works in translation.",
    founded: 1967,
  },
  {
    id: "dundurn-press",
    name: "Dundurn Press",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    genres: ["Fiction", "Non-fiction", "History", "Mystery", "Biography", "Young Adult"],
    description: "Canada's largest independent publisher. Actively seeks new Canadian voices across fiction, non-fiction, and YA. Known for its Canadian history and true crime titles.",
    website: "https://www.dundurn.com",
    submissionUrl: "https://www.dundurn.com/pages/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Actively looks for Canadian stories and Canadian authors.",
    founded: 1972,
  },
  {
    id: "ecw-press",
    name: "ECW Press",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    genres: ["Fiction", "Non-fiction", "Music", "Pop Culture", "Sports", "Mystery", "LGBTQ+"],
    description: "Toronto-based independent publisher with a diverse catalogue spanning fiction, pop culture, sports, and non-fiction. Actively accepts unsolicited manuscripts.",
    website: "https://www.ecwpress.com",
    submissionUrl: "https://www.ecwpress.com/pages/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    founded: 1974,
  },

  // ── United Kingdom ─────────────────────────────────────────────────────────
  {
    id: "bloomsbury",
    name: "Bloomsbury Publishing",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Fantasy", "Non-fiction", "Children's", "Academic"],
    description: "Publisher of Harry Potter and countless award-winning literary works. One of the most respected publishers in the world, with offices in London, New York, and Delhi.",
    website: "https://www.bloomsbury.com",
    submissionUrl: "https://www.bloomsbury.com/uk/authors-submissions/",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Accepts agented submissions. The Bloomsbury Academic imprint accepts direct academic submissions.",
    founded: 1986,
  },
  {
    id: "faber-faber",
    name: "Faber & Faber",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Poetry", "Drama", "Non-fiction", "Children's"],
    description: "One of the UK's most prestigious independent publishers, home to Nobel and Booker Prize winners. Known for exceptional literary fiction, poetry, and drama.",
    website: "https://www.faber.co.uk",
    submissionUrl: "https://www.faber.co.uk/about/submissions/",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Accepts submissions via literary agents. A very selective publisher focused on the finest writing.",
    founded: 1929,
  },
  {
    id: "canongate",
    name: "Canongate Books",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Graphic Novels", "International Fiction"],
    description: "Edinburgh-based independent publisher known for international literary fiction and translated works. Published Yann Martel's Life of Pi. Champions bold, boundary-crossing writing.",
    website: "https://www.canongate.co.uk",
    submissionUrl: "https://www.canongate.co.uk/submissions/",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Accepts agented submissions only.",
    founded: 1973,
  },
  {
    id: "orenda-books",
    name: "Orenda Books",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Crime Fiction", "Thriller", "Literary Fiction", "International Fiction", "Nordic Noir"],
    description: "Award-winning independent publisher specialising in crime fiction and international thrillers. Known for discovering outstanding crime writers from around the world.",
    website: "https://www.orendabooks.co.uk",
    submissionEmail: "submissions@orendabooks.co.uk",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Send the first 50 pages and a synopsis to their submissions email. Open to writers worldwide.",
    founded: 2014,
  },
  {
    id: "legend-press",
    name: "Legend Press",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Fiction", "Literary Fiction", "Commercial Fiction"],
    description: "UK independent publisher that actively seeks debut fiction. Runs regular competitions and manuscript calls open to unagented authors worldwide.",
    website: "https://www.legendpress.co.uk",
    submissionUrl: "https://www.legendpress.co.uk/submissions/",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Actively looking for debut literary and commercial fiction.",
    founded: 2005,
  },
  {
    id: "galley-beggar",
    name: "Galley Beggar Press",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    genres: ["Literary Fiction", "Short Stories", "Experimental Fiction"],
    description: "Independent publisher dedicated to exceptional literary fiction and short stories. Published Eimear McBride's A Girl Is a Half-formed Thing. Champion of bold, experimental writing.",
    website: "https://www.galleybeggar.co.uk",
    submissionUrl: "https://www.galleybeggar.co.uk/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    founded: 2012,
  },

  // ── Australia & New Zealand ────────────────────────────────────────────────
  {
    id: "allen-unwin",
    name: "Allen & Unwin",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    genres: ["Fiction", "Non-fiction", "Children's", "Young Adult", "Literary Fiction"],
    description: "Australia's leading independent publisher, producing about 80 Australian titles a year. Known for giving new authors their start and a strong commitment to Australian voices.",
    website: "https://www.allenandunwin.com",
    submissionUrl: "https://www.allenandunwin.com/about/for-authors",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "The Friday Pitch allows unpublished authors to send a synopsis and first chapter every Friday.",
    founded: 1976,
  },
  {
    id: "text-publishing",
    name: "Text Publishing",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    genres: ["Literary Fiction", "Non-fiction", "Essays", "Crime Fiction"],
    description: "Melbourne publisher known for award-winning Australian and international literary fiction. Publishes many Miles Franklin Award winners and Man Booker longlist authors.",
    website: "https://www.textpublishing.com.au",
    submissionUrl: "https://www.textpublishing.com.au/authors/submissions",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Accepts agented submissions. Also open to Australian authors submitting directly.",
    founded: 1990,
  },
  {
    id: "victoria-university-press",
    name: "Victoria University Press",
    country: "New Zealand",
    countryCode: "NZ",
    region: "Oceania",
    genres: ["Literary Fiction", "Poetry", "Non-fiction", "Short Stories", "Biography"],
    description: "New Zealand's premier literary publisher, producing the finest New Zealand writing including poetry, fiction, and essays. Publishes New Zealand authors exclusively.",
    website: "https://www.victoria.ac.nz/vup",
    submissionUrl: "https://www.victoria.ac.nz/vup/forauthors",
    acceptsUnsolicited: true,
    languages: ["English", "Māori"],
    notes: "Primarily publishes New Zealand authors.",
    founded: 1974,
  },

  // ── Germany ────────────────────────────────────────────────────────────────
  {
    id: "fischer-verlag",
    name: "S. Fischer Verlag",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "International Literature", "Philosophy"],
    description: "One of Germany's oldest and most prestigious publishers, founded in Berlin. Home to Thomas Mann, Sigmund Freud, and many Nobel Prize winners. Publishes German and international literature.",
    website: "https://www.fischerverlage.de",
    submissionEmail: "lektorat@fischerverlage.de",
    acceptsUnsolicited: false,
    languages: ["German"],
    notes: "Accepts submissions via literary agents. For international authors, contact through your local agent.",
    founded: 1886,
  },
  {
    id: "rowohlt",
    name: "Rowohlt Verlag",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    genres: ["Literary Fiction", "Thriller", "Crime", "Non-fiction", "Children's"],
    description: "Hamburg-based publishing house known for publishing international bestselling authors in German translation. One of the largest literary publishers in Germany.",
    website: "https://www.rowohlt.de",
    submissionUrl: "https://www.rowohlt.de/autorinnen-und-autoren/manuskript-einsenden",
    acceptsUnsolicited: true,
    languages: ["German"],
    notes: "Submit via their online form. Primarily interested in German-language manuscripts.",
    founded: 1908,
  },
  {
    id: "hanser",
    name: "Carl Hanser Verlag",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Children's", "International Literature"],
    description: "Munich publisher known for high literary standards and international literature in translation. Publishes many Nobel and Booker Prize authors in German translation.",
    website: "https://www.hanser-literaturverlage.de",
    submissionEmail: "info@hanser.de",
    acceptsUnsolicited: false,
    languages: ["German"],
    notes: "Highly selective. Best approached via a literary agent.",
    founded: 1928,
  },

  // ── France ─────────────────────────────────────────────────────────────────
  {
    id: "gallimard",
    name: "Éditions Gallimard",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    genres: ["Literary Fiction", "Poetry", "Non-fiction", "Philosophy", "Classics"],
    description: "France's most prestigious publisher, home to Sartre, Camus, Beauvoir, and nearly half of all French Nobel Prize winners in Literature. The pinnacle of French literary publishing.",
    website: "https://www.gallimard.fr",
    submissionEmail: "manuscrits@gallimard.fr",
    acceptsUnsolicited: true,
    languages: ["French"],
    notes: "Accepts unsolicited manuscripts by post or email. Expect a long response time.",
    founded: 1911,
  },
  {
    id: "actes-sud",
    name: "Actes Sud",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    genres: ["Literary Fiction", "International Fiction", "Non-fiction", "Poetry", "Theatre"],
    description: "Arles-based publisher known for international literature and translations. Published Nobel Prize winner Orhan Pamuk's French translations. A champion of world literature.",
    website: "https://www.actes-sud.fr",
    submissionEmail: "contact@actes-sud.fr",
    acceptsUnsolicited: true,
    languages: ["French"],
    notes: "Particularly interested in international literature and non-French-speaking authors.",
    founded: 1978,
  },
  {
    id: "editions-de-minuit",
    name: "Les Éditions de Minuit",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    genres: ["Literary Fiction", "Experimental Fiction", "Non-fiction"],
    description: "Legendary Paris publisher that emerged from the French Resistance. Published Samuel Beckett, Marguerite Duras, and the founders of the Nouveau Roman movement. Focuses on experimental and avant-garde writing.",
    website: "https://www.leseditionsdeminuit.fr",
    submissionEmail: "info@leseditionsdeminuit.fr",
    acceptsUnsolicited: false,
    languages: ["French"],
    notes: "Highly selective. Best approached via a literary agent.",
    founded: 1942,
  },

  // ── Spain & Latin America ──────────────────────────────────────────────────
  {
    id: "anagrama",
    name: "Editorial Anagrama",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    genres: ["Literary Fiction", "Crime Fiction", "Non-fiction", "Essays"],
    description: "Barcelona's most internationally prestigious publisher, known for the Premio Herralde literary prize. Has launched hundreds of Spanish and international literary careers.",
    website: "https://www.anagrama-ed.es",
    submissionEmail: "info@anagrama-ed.es",
    acceptsUnsolicited: true,
    languages: ["Spanish", "Catalan"],
    notes: "The Premio Herralde award accepts manuscript submissions annually in July.",
    founded: 1969,
  },
  {
    id: "tusquets",
    name: "Tusquets Editores",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    genres: ["Literary Fiction", "Essays", "Non-fiction", "Erotica", "International Literature"],
    description: "Barcelona publisher known for daring literary choices, international translations, and the Premi Tusquets literary award. Publishes top Spanish and Latin American authors.",
    website: "https://www.tusquetseditores.com",
    submissionEmail: "editorial@tusquetseditores.com",
    acceptsUnsolicited: false,
    languages: ["Spanish"],
    notes: "Accepts submissions via literary agents. Published García Márquez, Vargas Llosa, and Isabel Allende.",
    founded: 1969,
  },
  {
    id: "fce",
    name: "Fondo de Cultura Económica",
    country: "Mexico",
    countryCode: "MX",
    region: "Latin America",
    genres: ["Non-fiction", "Academic", "Literary Fiction", "Social Sciences", "History"],
    description: "Mexico's most important academic and literary publisher, with offices across Latin America and Spain. A cornerstone of Spanish-language intellectual publishing for over 80 years.",
    website: "https://www.fondodeculturaeconomica.com",
    submissionEmail: "editorial@fondodeculturaeconomica.com",
    acceptsUnsolicited: true,
    languages: ["Spanish"],
    notes: "Focus is on academic and serious literary work. The FCE Prize accepts manuscript submissions.",
    founded: 1934,
  },
  {
    id: "sexto-piso",
    name: "Sexto Piso Editorial",
    country: "Mexico",
    countryCode: "MX",
    region: "Latin America",
    genres: ["Literary Fiction", "Non-fiction", "Children's", "International Literature"],
    description: "Independent Mexico City publisher known for innovative literary fiction and international translations. One of the most exciting small publishers in the Spanish-speaking world.",
    website: "https://www.sextopiso.com",
    submissionEmail: "editorial@sextopiso.com",
    acceptsUnsolicited: true,
    languages: ["Spanish"],
    notes: "Actively seeks bold and original literary work in Spanish.",
    founded: 2003,
  },
  {
    id: "companhia-das-letras",
    name: "Companhia das Letras",
    country: "Brazil",
    countryCode: "BR",
    region: "Latin America",
    genres: ["Literary Fiction", "Non-fiction", "International Fiction", "History"],
    description: "Brazil's most prestigious literary publisher, responsible for bringing Nobel Prize winners and major international authors to Brazilian readers. Home to the best Brazilian contemporary authors.",
    website: "https://www.companhiadasletras.com.br",
    submissionEmail: "editorial@companhiadasletras.com.br",
    acceptsUnsolicited: false,
    languages: ["Portuguese"],
    notes: "Accepts agented submissions. One of the most selective publishers in Latin America.",
    founded: 1986,
  },
  {
    id: "intrínseca",
    name: "Editora Intrínseca",
    country: "Brazil",
    countryCode: "BR",
    region: "Latin America",
    genres: ["Young Adult", "Fiction", "Fantasy", "Romance", "Children's"],
    description: "Rio de Janeiro publisher responsible for the Portuguese translations of The Hunger Games, Twilight, and Game of Thrones. Also publishes original Brazilian fiction and YA.",
    website: "https://www.intrinseca.com.br",
    submissionUrl: "https://www.intrinseca.com.br/colecoes/submissao",
    acceptsUnsolicited: true,
    languages: ["Portuguese"],
    notes: "Actively seeking Brazilian authors in fiction and YA. Submit synopsis and sample chapters.",
    founded: 2007,
  },

  // ── Arab World & Middle East ───────────────────────────────────────────────
  {
    id: "dar-al-adab",
    name: "دار الآداب (Dar Al-Adab)",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Literary Fiction", "Poetry", "Short Stories", "Non-fiction", "Arab Literature", "Translated Literature"],
    description: "One of the most prestigious literary publishers in the Arab world, founded in Beirut. Has published many of the Arab world's greatest writers including Ghassan Kanafani, Elias Khoury, and Hanan Al-Shaykh.",
    website: "https://www.daraladab.com",
    submissionEmail: "info@daraladab.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    notes: "Beirut's leading literary press. Actively seeks original Arabic literary writing.",
    founded: 1956,
    rating: 4.8,
    submissionType: "both",
    logoColor: "#9f1239",
  },
  {
    id: "dar-al-shorouk",
    name: "دار الشروق (Dar Al-Shorouk)",
    country: "Egypt",
    countryCode: "EG",
    city: "Cairo",
    region: "Middle East & North Africa",
    genres: ["Fiction", "Non-fiction", "History", "Political Science", "Religion", "Children's", "Arab Literature"],
    description: "Egypt's largest and most influential publisher with offices in Cairo and Beirut. The go-to publisher for major Arab authors and intellectuals. Home to Naguib Mahfouz's celebrated editions.",
    website: "https://www.shorouk.com",
    submissionEmail: "editorial@shorouk.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    notes: "Accepts manuscript submissions directly. Strong distribution across all Arab countries.",
    founded: 1968,
    rating: 4.7,
    submissionType: "both",
    logoColor: "#b45309",
  },
  {
    id: "al-arabi",
    name: "دار العربي (Al-Arabi Publishing)",
    country: "Kuwait",
    countryCode: "KW",
    region: "Middle East & North Africa",
    genres: ["Fiction", "Poetry", "Cultural Studies", "Arab Literature"],
    description: "Kuwait-based publisher connected to the prestigious Al-Arabi magazine. Publishes literary and cultural works with broad distribution across the Gulf and Arab world.",
    website: "https://www.alarabimag.com",
    submissionEmail: "publishing@alarabimag.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 1958,
  },
  {
    id: "dar-al-saqi",
    name: "دار الساقي (Dar Al-Saqi)",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Literary Fiction", "Non-fiction", "History", "Politics", "Arab Literature", "Philosophy", "Biography"],
    description: "Beirut and London-based publisher specializing in Arabic literature and translations between Arabic and English. A bridge between Arab and international literary cultures for over 45 years.",
    website: "https://www.darsaqi.com",
    submissionEmail: "info@darsaqi.com",
    acceptsUnsolicited: true,
    languages: ["Arabic", "English"],
    notes: "Publishes in both Arabic and English. Actively seeks Arabic fiction for international audiences.",
    founded: 1976,
    rating: 4.6,
    submissionType: "both",
    logoColor: "#0891b2",
  },
  {
    id: "bloomsbury-qatar",
    name: "Bloomsbury Qatar Foundation Publishing",
    country: "Qatar",
    countryCode: "QA",
    region: "Middle East & North Africa",
    genres: ["Fiction", "Non-fiction", "Children's", "Academic", "Arab Literature"],
    description: "A joint venture between Bloomsbury UK and the Qatar Foundation, dedicated to promoting Arabic and international literature in the region. Publishes in both Arabic and English.",
    website: "https://www.bqfp.com.qa",
    submissionEmail: "submissions@bqfp.com.qa",
    acceptsUnsolicited: true,
    languages: ["Arabic", "English"],
    notes: "Actively seeks manuscripts in Arabic and about the Arab world.",
    founded: 2010,
  },
  {
    id: "kalimat",
    name: "كلمات (Kalimat Group)",
    country: "United Arab Emirates",
    countryCode: "AE",
    region: "Middle East & North Africa",
    genres: ["Children's", "Young Adult", "Fiction", "Arab Literature"],
    description: "UAE's leading children's book publisher. Committed to creating engaging Arabic content for young readers. Winner of multiple international awards for children's publishing.",
    website: "https://www.kalimat.ae",
    submissionEmail: "submissions@kalimat.ae",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    notes: "Primarily focused on children's and YA Arabic content.",
    founded: 2007,
  },
  {
    id: "hachette-antoine",
    name: "دار هاشيت أنطوان (Hachette Antoine)",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Fiction", "Non-fiction", "Children's", "Self-help", "Business", "Translated Literature", "Arab Literature"],
    description: "A partnership between France's Hachette Livre and Lebanon's Librairie Antoine. One of the most commercially successful publishers in the Arab world with strong regional distribution and a trusted bridge between French and Arabic literary cultures.",
    website: "https://www.hachette-antoine.com",
    submissionEmail: "editions@antoineonline.com",
    acceptsUnsolicited: true,
    languages: ["Arabic", "French"],
    founded: 1959,
    rating: 4.4,
    submissionType: "both",
    logoColor: "#0891b2",
  },

  // ── India & South Asia ─────────────────────────────────────────────────────
  {
    id: "harpercollins-india",
    name: "HarperCollins India",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    genres: ["Fiction", "Non-fiction", "Literary Fiction", "Self-help", "Children's", "Business"],
    description: "India's leading publisher of English-language books. Publishes India's biggest authors and actively seeks new voices across all categories. Strong domestic and international distribution.",
    website: "https://www.harpercollins.co.in",
    submissionEmail: "harpercollinsindiasubmissions@gmail.com",
    acceptsUnsolicited: true,
    languages: ["English", "Hindi"],
    notes: "Actively seeks manuscripts from Indian authors. Send synopsis and first three chapters.",
    founded: 1992,
  },
  {
    id: "aleph-book",
    name: "Aleph Book Company",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    genres: ["Literary Fiction", "Non-fiction", "Biography", "History", "Politics"],
    description: "Delhi-based independent publisher founded by veteran publisher David Davidar. Publishes serious literary fiction and important non-fiction. Known for curating exceptional writing.",
    website: "https://www.alephbookcompany.com",
    submissionEmail: "info@alephbookcompany.com",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Submit a synopsis and first 50 pages. Actively seeks Indian literary voices.",
    founded: 2011,
  },
  {
    id: "speaking-tiger",
    name: "Speaking Tiger Books",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    genres: ["Literary Fiction", "Non-fiction", "Essays", "Children's", "Environment"],
    description: "Delhi publisher committed to literary fiction and serious non-fiction, including environment and social issues. Known for publishing overlooked and underrepresented voices.",
    website: "https://www.speakingtiger.com",
    submissionEmail: "manuscripts@speakingtiger.com",
    acceptsUnsolicited: true,
    languages: ["English", "Hindi"],
    notes: "Welcomes direct submissions from authors. Particularly interested in regional Indian stories.",
    founded: 2014,
  },
  {
    id: "penguin-india",
    name: "Penguin Random House India",
    country: "India",
    countryCode: "IN",
    region: "South Asia",
    genres: ["Fiction", "Non-fiction", "Business", "Self-help", "Young Adult", "Children's"],
    description: "India's largest publisher and the subcontinent arm of the global Penguin Random House group. Publishes across all categories with both literary and commercial titles.",
    website: "https://www.penguinindia.com",
    submissionUrl: "https://www.penguinindia.com/pages/Submission-Guidelines",
    acceptsUnsolicited: true,
    languages: ["English", "Hindi"],
    notes: "Accepts unsolicited submissions from Indian authors.",
    founded: 1985,
  },

  // ── Nordic Countries ───────────────────────────────────────────────────────
  {
    id: "norstedts",
    name: "Norstedts",
    country: "Sweden",
    countryCode: "SE",
    region: "Europe",
    genres: ["Literary Fiction", "Crime Fiction", "Non-fiction", "Biography"],
    description: "Sweden's oldest and most respected publisher, home to Astrid Lindgren's literary estate and many of Sweden's finest authors. The benchmark for Swedish literary publishing.",
    website: "https://www.norstedts.se",
    submissionEmail: "info@norstedts.se",
    acceptsUnsolicited: false,
    languages: ["Swedish"],
    notes: "Accepts submissions via Swedish literary agents.",
    founded: 1823,
  },
  {
    id: "gyldendal-norway",
    name: "Gyldendal Norsk Forlag",
    country: "Norway",
    countryCode: "NO",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Crime Fiction", "Children's"],
    description: "Norway's largest and oldest publisher. Home to Nobel Prize winner Knut Hamsun and many of Norway's most celebrated authors. A central part of Norwegian cultural life.",
    website: "https://www.gyldendal.no",
    submissionEmail: "forfattere@gyldendal.no",
    acceptsUnsolicited: true,
    languages: ["Norwegian"],
    notes: "Accepts unsolicited manuscript submissions with a query letter.",
    founded: 1925,
  },
  {
    id: "otava",
    name: "Otava",
    country: "Finland",
    countryCode: "FI",
    region: "Europe",
    genres: ["Fiction", "Non-fiction", "Children's", "Educational"],
    description: "Finland's largest publisher and a cultural institution. Publishes the finest Finnish literature alongside international translations. Part of Finnish literary and cultural heritage.",
    website: "https://www.otava.fi",
    submissionEmail: "otava@otava.fi",
    acceptsUnsolicited: true,
    languages: ["Finnish", "Swedish"],
    notes: "Accepts manuscript submissions in Finnish and Swedish.",
    founded: 1890,
  },

  // ── Italy & Netherlands ────────────────────────────────────────────────────
  {
    id: "einaudi",
    name: "Giulio Einaudi Editore",
    country: "Italy",
    countryCode: "IT",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Poetry", "Essays", "Philosophy"],
    description: "Turin's literary jewel and Italy's most celebrated publisher. Home to Italo Calvino, Cesare Pavese, and Nobel Prize winners. The gold standard of Italian literary publishing.",
    website: "https://www.einaudi.it",
    submissionEmail: "info@einaudi.it",
    acceptsUnsolicited: false,
    languages: ["Italian"],
    notes: "Accepts submissions via literary agents. Publishes Italian and international literature.",
    founded: 1933,
  },
  {
    id: "feltrinelli",
    name: "Giangiacomo Feltrinelli Editore",
    country: "Italy",
    countryCode: "IT",
    region: "Europe",
    genres: ["Literary Fiction", "Politics", "Non-fiction", "International Literature"],
    description: "Milan-based publisher of international renown that published Doctor Zhivago and The Leopard. Known for political and literary courage and a strong international list.",
    website: "https://www.feltrinellieditore.it",
    submissionEmail: "editoria@feltrinelli.it",
    acceptsUnsolicited: false,
    languages: ["Italian"],
    notes: "Accepts agented submissions. Particularly open to international literary fiction.",
    founded: 1955,
  },
  {
    id: "de-bezige-bij",
    name: "De Bezige Bij",
    country: "Netherlands",
    countryCode: "NL",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Thriller", "Crime Fiction"],
    description: "Amsterdam's most prestigious literary publisher and a cornerstone of Dutch literary culture. Born from the Dutch Resistance, it has always stood for literary independence and quality.",
    website: "https://www.debezigebij.nl",
    submissionEmail: "lectoraat@debezigebij.nl",
    acceptsUnsolicited: true,
    languages: ["Dutch"],
    notes: "Accepts Dutch-language manuscript submissions.",
    founded: 1944,
  },

  // ── East Asia ──────────────────────────────────────────────────────────────
  {
    id: "bungeishunju",
    name: "文藝春秋 (Bungeishunju)",
    country: "Japan",
    countryCode: "JP",
    region: "East Asia",
    genres: ["Literary Fiction", "Non-fiction", "History", "Crime Fiction"],
    description: "One of Japan's most prestigious publishers and home to the Akutagawa Prize and Naoki Prize. Published many of Japan's greatest authors including Haruki Murakami.",
    website: "https://www.bunshun.co.jp",
    submissionEmail: "info@bunshun.co.jp",
    acceptsUnsolicited: false,
    languages: ["Japanese"],
    notes: "Accepts submissions via the Akutagawa and Naoki literary prizes for debut authors.",
    founded: 1923,
  },
  {
    id: "people-literature-china",
    name: "人民文学出版社 (People's Literature Publishing House)",
    country: "China",
    countryCode: "CN",
    region: "East Asia",
    genres: ["Literary Fiction", "Non-fiction", "Classics", "Poetry", "Children's"],
    description: "China's premier literary publisher under the state publishing system. Published virtually all major Chinese authors of the 20th and 21st centuries. The benchmark of Chinese literary publishing.",
    website: "https://www.rw.com.cn",
    submissionEmail: "rwcbs@126.com",
    acceptsUnsolicited: true,
    languages: ["Chinese (Simplified)"],
    notes: "Primarily publishes Chinese-language works by Chinese authors.",
    founded: 1951,
  },
  {
    id: "changbi",
    name: "창비 (Changbi Publishers)",
    country: "South Korea",
    countryCode: "KR",
    region: "East Asia",
    genres: ["Literary Fiction", "Poetry", "Non-fiction", "Children's", "Social Criticism"],
    description: "South Korea's leading independent literary publisher. Known for progressive social commentary and some of Korea's most celebrated novels including Han Kang's The Vegetarian.",
    website: "https://www.changbi.com",
    submissionEmail: "letters@changbi.com",
    acceptsUnsolicited: true,
    languages: ["Korean"],
    notes: "Actively seeks original Korean-language literary manuscripts.",
    founded: 1974,
  },

  // ── Africa ─────────────────────────────────────────────────────────────────
  {
    id: "cassava-republic",
    name: "Cassava Republic Press",
    country: "Nigeria",
    countryCode: "NG",
    region: "Africa",
    genres: ["Literary Fiction", "Crime Fiction", "Romance", "Children's", "Young Adult"],
    description: "Africa's most internationally recognized independent publisher, with offices in Abuja and London. Publishing African stories for African and global audiences. Home to the Caine Prize-winning tradition.",
    website: "https://www.cassavarepublic.biz",
    submissionUrl: "https://www.cassavarepublic.biz/pages/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Actively seeking manuscripts from African authors. Focus on authentic African stories.",
    founded: 2006,
  },
  {
    id: "farafina",
    name: "Farafina Books",
    country: "Nigeria",
    countryCode: "NG",
    region: "Africa",
    genres: ["Literary Fiction", "Non-fiction", "African Literature"],
    description: "Lagos-based publisher that launched Chimamanda Ngozi Adichie's career with Purple Hibiscus. A cornerstone of contemporary Nigerian literary publishing.",
    website: "https://www.farafinabooks.com",
    submissionEmail: "info@farafinabooks.com",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Focus on African literary fiction and non-fiction.",
    founded: 2004,
  },
  {
    id: "storymoja",
    name: "Storymoja Africa",
    country: "Kenya",
    countryCode: "KE",
    region: "Africa",
    genres: ["Children's", "Young Adult", "Fiction", "African Literature"],
    description: "Nairobi publisher dedicated to creating quality reading material for African children and young adults. Focused on African stories, African settings, and African protagonists.",
    website: "https://www.storymoja.com",
    submissionEmail: "info@storymoja.com",
    acceptsUnsolicited: true,
    languages: ["English", "Swahili"],
    notes: "Primarily publishes children's and YA content set in Africa.",
    founded: 2008,
  },
  {
    id: "jonathan-ball",
    name: "Jonathan Ball Publishers",
    country: "South Africa",
    countryCode: "ZA",
    region: "Africa",
    genres: ["Non-fiction", "Fiction", "Biography", "History", "Politics", "Sport"],
    description: "South Africa's leading independent publisher of non-fiction and fiction. Known for publishing South African stories with a strong local and African perspective.",
    website: "https://www.jonathanball.co.za",
    submissionEmail: "publishing@jonathanball.co.za",
    acceptsUnsolicited: true,
    languages: ["English", "Afrikaans"],
    notes: "Primarily focused on South African and African content.",
    founded: 1976,
  },

  // ── Poland & Eastern Europe ────────────────────────────────────────────────
  {
    id: "znak",
    name: "Wydawnictwo Znak",
    country: "Poland",
    countryCode: "PL",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Spirituality", "Biography", "History"],
    description: "Kraków's most respected publisher, known for quality literary fiction, religious writing, and major Polish and international non-fiction. Consistently wins Poland's top literary prizes.",
    website: "https://www.znak.com.pl",
    submissionEmail: "redakcja@znak.com.pl",
    acceptsUnsolicited: true,
    languages: ["Polish"],
    notes: "Accepts Polish-language manuscript submissions.",
    founded: 1959,
    rating: 4.3,
    submissionType: "both",
    logoColor: "#1d4ed8",
  },

  // ── Global Big 5 ──────────────────────────────────────────────────────────
  {
    id: "harpercollins",
    name: "HarperCollins Publishers",
    country: "United States",
    countryCode: "US",
    city: "New York",
    region: "North America",
    genres: ["Fiction", "Literary Fiction", "Non-fiction", "Children's", "Thriller", "Fantasy", "Romance", "Biography"],
    description: "One of the world's largest publishing groups with imprints spanning HarperOne, Avon, Morrow, and HarperTeen. Publishes 10,000+ new titles per year across genres and languages.",
    website: "https://www.harpercollins.com",
    submissionUrl: "https://www.harpercollins.com/pages/submissions",
    acceptsUnsolicited: false,
    languages: ["English", "Spanish", "French"],
    notes: "Generally accepts submissions via literary agents. HarperCollins Christian Publishing accepts unagented submissions.",
    founded: 1817,
    rating: 4.7,
    submissionType: "digital",
    logoColor: "#7c3aed",
  },
  {
    id: "simon-schuster",
    name: "Simon & Schuster",
    country: "United States",
    countryCode: "US",
    city: "New York",
    region: "North America",
    genres: ["Fiction", "Non-fiction", "Memoir", "Thriller", "Politics", "Business", "Self-help"],
    description: "A prestigious publisher with iconic imprints including Scribner, Atria, and Gallery Books. Known for major literary fiction, political books, and bestselling non-fiction.",
    website: "https://www.simonandschuster.com",
    submissionUrl: "https://www.simonandschuster.com/about/submissions",
    acceptsUnsolicited: false,
    languages: ["English"],
    notes: "Acquired by KKR in 2023. Accepts agented manuscripts only.",
    founded: 1924,
    rating: 4.6,
    submissionType: "digital",
    logoColor: "#0891b2",
  },
  {
    id: "hachette-livre",
    name: "Hachette Livre",
    country: "France",
    countryCode: "FR",
    city: "Paris",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "History", "Biography", "Crime Fiction", "Children's"],
    description: "France's largest publisher and second largest in the world, home to Larousse, Fayard, Grasset, and Calmann-Lévy. Dominates French literary culture.",
    website: "https://www.hachette.fr",
    submissionEmail: "manuscrits@hachette.fr",
    acceptsUnsolicited: true,
    languages: ["French"],
    notes: "Accepts unsolicited manuscripts at several imprints. Grasset accepts direct queries.",
    founded: 1826,
    rating: 4.7,
    submissionType: "both",
    logoColor: "#0d9488",
  },
  {
    id: "planeta",
    name: "Grupo Planeta",
    country: "Spain",
    countryCode: "ES",
    city: "Barcelona",
    region: "Europe",
    genres: ["Literary Fiction", "Non-fiction", "Biography", "Crime Fiction", "History", "Self-help"],
    description: "Spain's dominant publishing group and top publisher across Latin America. Hosts Premio Planeta, one of the world's richest literary prizes. Strong presence in 20+ Spanish-speaking markets.",
    website: "https://www.planeta.es",
    submissionUrl: "https://www.planeta.es/autores",
    acceptsUnsolicited: true,
    languages: ["Spanish", "Catalan"],
    notes: "Runs the €1M Premio Planeta annually — open submissions. Also accepts direct query letters.",
    founded: 1949,
    rating: 4.5,
    submissionType: "digital",
    logoColor: "#b45309",
  },
  {
    id: "suhrkamp",
    name: "Suhrkamp Verlag",
    country: "Germany",
    countryCode: "DE",
    city: "Berlin",
    region: "Europe",
    genres: ["Literary Fiction", "Poetry", "Philosophy", "Drama", "Theory", "Non-fiction"],
    description: "Germany's most prestigious literary publisher, home to Nobel laureates and defining voices of 20th-century literature. The go-to house for serious international literary fiction in German translation.",
    website: "https://www.suhrkamp.de",
    submissionEmail: "info@suhrkamp.de",
    acceptsUnsolicited: false,
    languages: ["German"],
    notes: "Highly selective. Submissions primarily through agents or established contacts.",
    founded: 1950,
    rating: 4.9,
    submissionType: "both",
    logoColor: "#374151",
  },
  {
    id: "mondadori",
    name: "Arnoldo Mondadori Editore",
    country: "Italy",
    countryCode: "IT",
    city: "Milan",
    region: "Europe",
    genres: ["Literary Fiction", "Crime Fiction", "Non-fiction", "Biography", "Children's", "Romance"],
    description: "Italy's largest and most prestigious publisher. Part of the Mondadori Group which includes Einaudi and Rizzoli. Has published virtually every major Italian and international author.",
    website: "https://www.mondadori.it",
    submissionEmail: "redazione@mondadori.it",
    acceptsUnsolicited: false,
    languages: ["Italian"],
    notes: "Agent submissions preferred. Mondadori's Einaudi imprint is Italy's most literary.",
    founded: 1907,
    rating: 4.6,
    submissionType: "both",
    logoColor: "#dc2626",
  },
  {
    id: "kodansha",
    name: "Kodansha",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    region: "East Asia",
    genres: ["Fiction", "Manga", "Young Adult", "Non-fiction", "Biography", "Science Fiction"],
    description: "Japan's largest publisher and a major global force in manga, literary fiction, and popular culture. Kodansha International actively co-publishes English-language content.",
    website: "https://www.kodansha.co.jp",
    submissionUrl: "https://www.kodansha.co.jp/books/",
    acceptsUnsolicited: false,
    languages: ["Japanese", "English"],
    notes: "Submissions via agents. Kodansha Comics accepts pitch decks from illustrators.",
    founded: 1909,
    rating: 4.5,
    submissionType: "digital",
    logoColor: "#b45309",
  },

  // ── MENA Extended ────────────────────────────────────────────────────────
  {
    id: "riad-rayyes",
    name: "Riad El-Rayyes Books",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Poetry", "Memoirs", "History", "Politics"],
    description: "One of Beirut's most distinguished literary publishers, known for publishing iconic Arab poets and novelists. Has shaped contemporary Arab literature through decades of influential publishing.",
    website: "https://www.rayyesbooks.com",
    submissionEmail: "info@rayyesbooks.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 1985,
    rating: 4.5,
    submissionType: "both",
    logoColor: "#7c3aed",
  },
  {
    id: "dar-al-maaref",
    name: "Dar Al-Maaref",
    country: "Egypt",
    countryCode: "EG",
    city: "Cairo",
    region: "Middle East & North Africa",
    genres: ["Academic", "Non-fiction", "Arab Literature", "History", "Education", "Science"],
    description: "Egypt's oldest and most venerable publishing institution, founded by royal decree. Publishes academic works, encyclopedias, school textbooks, and celebrated literary editions across Arabic-speaking countries.",
    website: "https://www.darmaaref.com",
    submissionEmail: "info@darmaaref.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 1890,
    rating: 4.4,
    submissionType: "both",
    logoColor: "#065f46",
  },
  {
    id: "madarek-publishing",
    name: "Madarek Publishing",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Dubai",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Self-help", "Business", "Young Adult"],
    description: "Dubai-based publisher recognized for energetic modern Arab voices and Gulf literature. Known for discovering new Emirati and Gulf Coast writers and connecting them to pan-Arab readership.",
    website: "https://www.madarek.ae",
    submissionEmail: "editor@madarek.ae",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    notes: "Strongly encourages Emirati, Gulf, and young Arab authors to submit.",
    founded: 2005,
    rating: 4.2,
    submissionType: "digital",
    logoColor: "#0e7490",
  },
  {
    id: "jarir-bookstore",
    name: "Jarir Bookstore Publishing",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Self-help", "Religion", "Academic", "Children's"],
    description: "The Arabian Peninsula's largest book retailer with a growing in-house publishing arm. Reaches millions of readers across Saudi Arabia, GCC, and the broader Arab world.",
    website: "https://www.jarir.com",
    submissionEmail: "publishing@jarir.com",
    acceptsUnsolicited: true,
    languages: ["Arabic", "English"],
    notes: "Looking for commercially viable titles with broad Gulf and pan-Arab appeal.",
    founded: 1979,
    rating: 4.3,
    submissionType: "both",
    logoColor: "#166534",
  },
  {
    id: "arab-scientific-publishers",
    name: "Arab Scientific Publishers (ASP)",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Academic", "Science", "Medicine", "Engineering", "Education", "Non-fiction"],
    description: "Leading academic publisher in the Arab world, specializing in scientific, medical, and technical titles. Distribution network spans 22 Arab countries with over 5,000 titles in print.",
    website: "https://www.asp.com.lb",
    submissionEmail: "info@asp.com.lb",
    acceptsUnsolicited: true,
    languages: ["Arabic", "English", "French"],
    founded: 1986,
    rating: 4.3,
    submissionType: "both",
    logoColor: "#1d4ed8",
  },
  {
    id: "dar-al-hadaeq",
    name: "Dar Al-Hadaeq",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Children's", "Young Adult", "Fiction", "Arab Literature"],
    description: "Beirut's leading publisher of children's and young adult literature in Arabic. Pioneers in producing bilingual Arabic-English children's books and nurturing the next generation of Arab readers.",
    website: "https://www.darhadaeq.com",
    submissionEmail: "info@darhadaeq.com",
    acceptsUnsolicited: true,
    languages: ["Arabic", "English"],
    notes: "Specializes exclusively in content for readers under 18.",
    founded: 1995,
    rating: 4.4,
    submissionType: "both",
    logoColor: "#d97706",
  },
  {
    id: "manshurat-al-jamal",
    name: "Manshurat Al-Jamal",
    country: "Germany",
    countryCode: "DE",
    city: "Cologne",
    region: "Europe",
    genres: ["Arab Literature", "Literary Fiction", "Poetry", "Political Writing", "Translated Literature"],
    description: "Arab diaspora publisher based in Cologne, Germany. Bridges the Arab literary world with European audiences, publishing critical and experimental Arab writing alongside translations of world literature into Arabic.",
    website: "https://www.aljamalpress.com",
    submissionEmail: "info@aljamalpress.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    notes: "Focus on politically engaged, experimental, and diaspora Arab voices. Open to bold, unconventional manuscripts.",
    founded: 1992,
    rating: 4.6,
    submissionType: "both",
    logoColor: "#9f1239",
  },
  {
    id: "dar-attanweer",
    name: "Dar Attanweer",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Non-fiction", "Philosophy", "Science", "Translated Literature"],
    description: "Progressive Beirut publisher committed to Enlightenment values and free thought. Publishes cutting-edge Arab fiction alongside pivotal translations of world philosophy and science into Arabic.",
    website: "https://www.tanweer-pub.com",
    submissionEmail: "info@tanweer-pub.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 2007,
    rating: 4.5,
    submissionType: "digital",
    logoColor: "#7c3aed",
  },
  {
    id: "arab-media-group",
    name: "Arab Media Group (Hamdan)",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Abu Dhabi",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Non-fiction", "Culture", "Heritage"],
    description: "Abu Dhabi's prestigious cultural publishing arm, closely affiliated with UAE government cultural initiatives and the Abu Dhabi International Book Fair. Strong supporter of Emirati writers and Gulf heritage.",
    website: "https://www.admf.ae",
    submissionEmail: "info@admf.ae",
    acceptsUnsolicited: true,
    languages: ["Arabic", "English"],
    notes: "Often co-sponsors UAE Book Award-winning titles.",
    founded: 1998,
    rating: 4.2,
    submissionType: "both",
    logoColor: "#0f766e",
  },
  {
    id: "al-kamel-verlag",
    name: "Al-Kamel Verlag",
    country: "Germany",
    countryCode: "DE",
    city: "Cologne",
    region: "Europe",
    genres: ["Arab Literature", "Poetry", "Literary Fiction", "Translated Literature", "History"],
    description: "Cologne-based publisher specializing in contemporary Arabic literature in German translation and Arabic-language publishing for the European diaspora. Has introduced dozens of major Arab writers to German readers.",
    website: "https://www.al-kamel.de",
    submissionEmail: "info@al-kamel.de",
    acceptsUnsolicited: true,
    languages: ["Arabic", "German"],
    founded: 1991,
    rating: 4.4,
    submissionType: "both",
    logoColor: "#374151",
  },
  {
    id: "noon-publishers",
    name: "Noon Publishers",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Riyadh",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Young Adult", "Romance", "Thriller"],
    description: "Riyadh's fastest-growing contemporary publisher, known for publishing bold, modern Saudi voices and popular fiction. Actively seeks young Saudi authors and genre fiction that resonates with Gulf youth.",
    website: "https://www.noon.sa",
    submissionEmail: "editorial@noon.sa",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    notes: "Strong commercial focus; interested in plot-driven fiction, YA, and popular non-fiction.",
    founded: 2015,
    rating: 4.1,
    submissionType: "digital",
    logoColor: "#dc2626",
  },
  {
    id: "dar-al-karma",
    name: "Dar Al-Karma",
    country: "Egypt",
    countryCode: "EG",
    city: "Cairo",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Young Adult", "Thriller", "Romance"],
    description: "Cairo's vibrant independent publisher with a fresh voice, known for commercial Arabic fiction and discovering emerging Egyptian novelists. A key launchpad for contemporary Egyptian literary voices.",
    website: "https://www.darkarma.net",
    submissionEmail: "manuscripts@darkarma.net",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 2010,
    rating: 4.2,
    submissionType: "digital",
    logoColor: "#b45309",
  },
  {
    id: "dar-al-tanweer-maroc",
    name: "Manshurat Difaf",
    country: "Morocco",
    countryCode: "MA",
    city: "Casablanca",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Poetry", "Non-fiction", "Translated Literature"],
    description: "Casablanca publisher leading Morocco's literary renaissance, championing Maghrebi voices and publishing North African fiction in Arabic and French. Bridge between sub-Saharan Africa and the Arab literary world.",
    website: "https://www.difaf.net",
    submissionEmail: "contact@difaf.net",
    acceptsUnsolicited: true,
    languages: ["Arabic", "French"],
    founded: 2008,
    rating: 4.3,
    submissionType: "both",
    logoColor: "#c2410c",
  },
  {
    id: "elias-modern-publishing",
    name: "Elias Modern Publishing",
    country: "Egypt",
    countryCode: "EG",
    city: "Cairo",
    region: "Middle East & North Africa",
    genres: ["Academic", "Education", "Children's", "Dictionaries", "Non-fiction"],
    description: "Egypt's premier educational publisher producing the authoritative modern Arabic dictionaries, children's encyclopedias, and educational materials used across Arabic-speaking countries.",
    website: "https://www.eliaspublishing.com",
    submissionEmail: "info@eliaspublishing.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 1913,
    rating: 4.5,
    submissionType: "both",
    logoColor: "#065f46",
  },
  {
    id: "dar-al-farabi",
    name: "Dar Al-Farabi",
    country: "Lebanon",
    countryCode: "LB",
    city: "Beirut",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Non-fiction", "Political Writing", "Memoirs"],
    description: "Left-leaning Beirut publisher that has been a home for Arab intellectuals and progressive political thinkers for over 60 years. Published landmark works of Palestinian, Lebanese, and pan-Arab literature.",
    website: "https://www.dar-alfarabi.com",
    submissionEmail: "info@dar-alfarabi.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 1961,
    rating: 4.4,
    submissionType: "both",
    logoColor: "#dc2626",
  },

  // ── Gulf & Levant ────────────────────────────────────────────────────────
  {
    id: "dar-al-hadaf",
    name: "Dar Al-Hadaf (Kuwait)",
    country: "Kuwait",
    countryCode: "KW",
    city: "Kuwait City",
    region: "Middle East & North Africa",
    genres: ["Arab Literature", "Fiction", "Self-help", "Religion", "Children's"],
    description: "Kuwait's established cultural publisher with regional distribution across the GCC. Actively supports Kuwaiti writers and Gulf voices, with a strong children's and educational catalogue.",
    website: "https://www.darhadaf.com",
    submissionEmail: "info@darhadaf.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    founded: 1980,
    rating: 4.0,
    submissionType: "both",
    logoColor: "#0f766e",
  },
  {
    id: "arab-institute-publishing",
    name: "Arab Institute for Research & Publishing",
    country: "Jordan",
    countryCode: "JO",
    city: "Amman",
    region: "Middle East & North Africa",
    genres: ["Academic", "History", "Non-fiction", "Arab Literature", "Politics", "Social Sciences"],
    description: "Amman-based academic publisher with the largest Arabic-language scholarly catalogue in the social sciences and humanities. Distributes to over 50 countries and serves leading Arab universities.",
    website: "https://www.aiarp.com",
    submissionEmail: "info@aiarp.com",
    acceptsUnsolicited: true,
    languages: ["Arabic"],
    notes: "Focus on academic and research-based works. Peer review required for academic submissions.",
    founded: 1969,
    rating: 4.5,
    submissionType: "both",
    logoColor: "#1d4ed8",
  },
  // ── Additional International ───────────────────────────────────────────────
  {
    id: "graywolf-press",
    name: "Graywolf Press",
    country: "United States",
    countryCode: "US",
    city: "Minneapolis",
    region: "North America",
    genres: ["Literary Fiction", "Poetry", "Non-fiction", "Essay", "Translated Literature"],
    description: "Minneapolis-based independent press celebrated for literary fiction, poetry, and essay. A non-profit publisher known for publishing vital, beautiful books that make a difference — multiple National Book Award and Pulitzer winners.",
    website: "https://www.graywolfpress.org",
    submissionUrl: "https://www.graywolfpress.org/pages/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Accepts queries directly. Strong in translated literature and debut literary fiction.",
    founded: 1974,
    rating: 4.7,
    submissionType: "digital",
    logoColor: "#374151",
  },
  {
    id: "restless-books",
    name: "Restless Books",
    country: "United States",
    countryCode: "US",
    city: "Brooklyn",
    region: "North America",
    genres: ["Translated Literature", "Literary Fiction", "Non-fiction", "Memoir"],
    description: "Brooklyn's premier international literature publisher, dedicated to extraordinary voices from outside the English-speaking world. Home to award-winning translations from Arabic, Spanish, French, and many more languages.",
    website: "https://www.restlessbooks.org",
    submissionEmail: "editors@restlessbooks.org",
    submissionUrl: "https://www.restlessbooks.org/pages/submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Particularly interested in works in translation, especially from underrepresented languages.",
    founded: 2013,
    rating: 4.5,
    submissionType: "digital",
    logoColor: "#dc2626",
  },
  {
    id: "interlink-publishing",
    name: "Interlink Publishing",
    country: "United States",
    countryCode: "US",
    city: "Northampton",
    region: "North America",
    genres: ["Arab Literature", "Translated Literature", "Non-fiction", "Politics", "Travel", "Cookbooks"],
    description: "Massachusetts publisher specializing in international and Arab literature in English translation. Interlink's Clockroot Books imprint is a leading portal for Arabic fiction in English. Known for Palestinian and Arab World Writings series.",
    website: "https://www.interlinkbooks.com",
    submissionEmail: "info@interlinkbooks.com",
    submissionUrl: "https://www.interlinkbooks.com/pages/manuscript-submissions",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Particularly interested in Arabic, Middle Eastern, and Global South literature in translation.",
    founded: 1987,
    rating: 4.4,
    submissionType: "both",
    logoColor: "#0891b2",
  },
  {
    id: "arc-publications",
    name: "ARC Publications",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Todmorden",
    region: "Europe",
    genres: ["Poetry", "Translated Literature", "Literary Fiction"],
    description: "UK's leading specialist poetry publisher with an international reputation. Particularly known for publishing translated poetry from the Arab World, Eastern Europe, and Asia. Accepts collections from both established and emerging poets.",
    website: "https://www.arcpublications.co.uk",
    submissionEmail: "arc.publications@btconnect.com",
    acceptsUnsolicited: true,
    languages: ["English"],
    notes: "Actively seeks Arabic poetry in English translation.",
    founded: 1969,
    rating: 4.5,
    submissionType: "both",
    logoColor: "#b45309",
  },
];

export const REGIONS = [
  "All Regions",
  "North America",
  "Europe",
  "Middle East & North Africa",
  "South Asia",
  "East Asia",
  "Latin America",
  "Oceania",
  "Africa",
];

export const ALL_GENRES = [
  "All Genres",
  "Literary Fiction",
  "Fiction",
  "Non-fiction",
  "Arab Literature",
  "Translated Literature",
  "Crime Fiction",
  "Thriller",
  "Science Fiction",
  "Fantasy",
  "Romance",
  "Young Adult",
  "Children's",
  "Poetry",
  "Biography",
  "Memoir",
  "History",
  "Academic",
  "Self-help",
  "Business",
  "Philosophy",
  "Politics",
  "Religion",
  "African Literature",
  "Manga",
  "Essay",
];

export const SUBMISSION_TYPES = [
  { value: "all", label: "All Types" },
  { value: "digital", label: "Digital Only" },
  { value: "physical", label: "Physical / Post" },
  { value: "both", label: "Digital & Physical" },
];

export const COUNTRIES: { name: string; code: string; region: string }[] = [
  { name: "United States", code: "US", region: "North America" },
  { name: "Canada", code: "CA", region: "North America" },
  { name: "United Kingdom", code: "GB", region: "Europe" },
  { name: "Australia", code: "AU", region: "Oceania" },
  { name: "New Zealand", code: "NZ", region: "Oceania" },
  { name: "Germany", code: "DE", region: "Europe" },
  { name: "France", code: "FR", region: "Europe" },
  { name: "Spain", code: "ES", region: "Europe" },
  { name: "Italy", code: "IT", region: "Europe" },
  { name: "Netherlands", code: "NL", region: "Europe" },
  { name: "Sweden", code: "SE", region: "Europe" },
  { name: "Norway", code: "NO", region: "Europe" },
  { name: "Finland", code: "FI", region: "Europe" },
  { name: "Poland", code: "PL", region: "Europe" },
  { name: "Mexico", code: "MX", region: "Latin America" },
  { name: "Brazil", code: "BR", region: "Latin America" },
  { name: "Argentina", code: "AR", region: "Latin America" },
  { name: "Colombia", code: "CO", region: "Latin America" },
  { name: "Lebanon", code: "LB", region: "Middle East & North Africa" },
  { name: "Egypt", code: "EG", region: "Middle East & North Africa" },
  { name: "Saudi Arabia", code: "SA", region: "Middle East & North Africa" },
  { name: "United Arab Emirates", code: "AE", region: "Middle East & North Africa" },
  { name: "Kuwait", code: "KW", region: "Middle East & North Africa" },
  { name: "Qatar", code: "QA", region: "Middle East & North Africa" },
  { name: "Jordan", code: "JO", region: "Middle East & North Africa" },
  { name: "Morocco", code: "MA", region: "Middle East & North Africa" },
  { name: "Tunisia", code: "TN", region: "Middle East & North Africa" },
  { name: "Algeria", code: "DZ", region: "Middle East & North Africa" },
  { name: "India", code: "IN", region: "South Asia" },
  { name: "Pakistan", code: "PK", region: "South Asia" },
  { name: "Bangladesh", code: "BD", region: "South Asia" },
  { name: "Japan", code: "JP", region: "East Asia" },
  { name: "China", code: "CN", region: "East Asia" },
  { name: "South Korea", code: "KR", region: "East Asia" },
  { name: "Nigeria", code: "NG", region: "Africa" },
  { name: "Kenya", code: "KE", region: "Africa" },
  { name: "South Africa", code: "ZA", region: "Africa" },
  { name: "Ghana", code: "GH", region: "Africa" },
  { name: "Ethiopia", code: "ET", region: "Africa" },
];
